version: '3.1'
services:
  jira:
    restart: always
    container_name: jira
    image: ealebed/jira:7.5.0
    links:
      - database
    ports:
      - "8080:8080"
    environment:
      - "CATALINA_OPTS= -Xms768m -Xmx2536m"
    volumes:
      - /opt/jira:/var/atlassian/jira

  confluence:
    restart: always
    container_name: confluence
    image: ealebed/confluence:6.3.4
    links:
      - database
    ports:
      - "8090:8090"
    volumes:
      - /opt/confluence:/var/atlassian/confluence

  database:
    restart: always
    container_name: percona
    image: percona:5.7
    environment:
#      - MYSQL_DATABASE=confluencedb
      - MYSQL_DATABASE=jiradb
#      - MYSQL_USER=cuser
      - MYSQL_USER=jirauser
#      - MYSQL_PASSWORD=<cuser_pass_here>
      - MYSQL_PASSWORD=<jiradb_pass_here>
      - MYSQL_ROOT_PASSWORD=<root_pass_here>
    volumes:
      - /opt/percona:/var/lib/mysql
    ports:
      - "3306:3306"
    command:
      - '--collation-server=utf8_bin'
      - '--character-set-server=utf8'
      - '--max_allowed_packet=34M'
      - '--innodb_log_file_size=256M'

  nginx:
    restart: always
    container_name: nginx
    image: nginx:1.12-alpine
    ports:
      - "80:80"
    volumes:
      - nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - jira
      - confluence
